# permissions for end users to view aroclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: arocluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: aro-controller
    app.kubernetes.io/part-of: aro-controller
    app.kubernetes.io/managed-by: kustomize
  name: arocluster-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - aroclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - aroclusters/status
  verbs:
  - get
