apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AROControlPlane
metadata:
  labels:
    app.kubernetes.io/name: arocontrolplane
    app.kubernetes.io/instance: arocontrolplane-sample
    app.kubernetes.io/part-of: aro-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: aro-controller
  name: arocontrolplane-sample
spec:
  # TODO(user): Add fields here
